package com.aftersales.platform.agent.plan;

/**
 * Planner 可输出的动作白名单，避免模型生成任意方法名或越权操作。
 */
public enum PlanAction {
    GET_LATEST_ORDER,
    CHECK_DELAYED_SHIPMENT,
    GET_PRODUCT,
    GET_AFTER_SALES_POLICY,
    CREATE_TICKET,
    GENERATE_AFTER_SALES_REPLY,
    UPDATE_TICKET_REPLY,
    GET_ORDER,
    VALIDATE_CANCELLABLE,
    CREATE_CANCEL_APPROVAL,
    CANCEL_ORDER,
    SEARCH_PRODUCTS,
    GENERATE_PRODUCT_ADVICE,
    RETURN_UNSUPPORTED
}
