package com.aftersales.platform.agent.plan;

public enum PlanAction {
    GET_LATEST_ORDER,
    CHECK_DELAYED_SHIPMENT,
    GET_PRODUCT,
    GET_AFTER_SALES_POLICY,
    CREATE_TICKET,
    GENERATE_AFTER_SALES_REPLY,
    UPDATE_TICKET_REPLY,
    GET_ORDER,
    VALIDATE_CANCELLABLE,
    CREATE_CANCEL_APPROVAL,
    CANCEL_ORDER,
    SEARCH_PRODUCTS,
    GENERATE_PRODUCT_ADVICE,
    RETURN_UNSUPPORTED
}
